name: Demo Of Variables And Context

on:
  workflow_dispatch:
    inputs:
      should_fail:
        description: 'Shall the step fail? (yes/no)'
        required: true
        type: string
        default: 'no'

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - name: Step that can fail
      run: |
        echo "Fail check..."
        if ["${{inputs.should_fail}}" = "yes"]; then
          exit 1
        fi
    - uses: actions/checkout@v4
    - name: Build-solution
      run: dotnet build
      
  github-context:
    runs-on: ubuntu-latest
    steps:
    - name: Print-Github-context-info
      run: echo "${{toJson(github)}}"
    - name: Print-repo-name
      run: echo "${{github.repository}}"
    - name: Print-event
      run: echo "${{github.event_name}}"
      
  job-context:
    runs-on: ubuntu-latest
    steps:
    - name: Print-job-context
      run: echo "${{toJSON(job)}}"
    - name: Print-runner-context
      run: echo "${{toJSON(runner)}}"
    - name: Print-job-status
      run: echo "${{job.status}}"
    - name: Print-runner-os
      run: echo "${{runner.os}}"
      
  all-good:
    runs-on: ubuntu-latest
    needs: [build-project, github-context, job-context]
    if: success()
    steps:
    - name: Print All good
      run: echo "All good!"

  failure-handler:
    runs-on: ubuntu-latest
    needs: [build-project, github-context, job-context]
    if: failure()
    steps:
    - name: Print Nothing good
      run: echo "Nothing good!"
      
