name: Secrets
# Create a workflow that triggers on dispatch
# 1. Print our slogan
# 2. Guess our magic number

on: 
  workflow_dispatch:
    inputs:
      num:
        type: string
        description: "Selecet number to guess"
        default: "3"

# 1
jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vars.SLOGAN }}
    steps:
    - run: echo ${{ vars.SLOGAN }}
    - run: echo $SLOGAN
  
# 2
  guess-magic-number:
    runs-on: ubuntu-latest
    env:
      MY_MAGIC_NUMBER: ${{ vars.MY_MAGIC_NUMBER }}
    steps:
    - name: Print Magic Number
      run: echo ${{ secrets.MY_MAGIC_NUMBER}}
      
    - name: Print Magic Number With Environment Variable
      run: echo $MY_MAGIC_NUMBER

    - name: Guess Magic Number
      run: |
        if ["${{secrets.MY_SECRET_NUMBER}}" = "${{inputs.num}}"]; then
          echo "Yay! The magic number was ${{inputs.num}}"
        fi
      
