name: Variable_Tests

on: 
  workflow_dispatch:

jobs:
  print-my-variable:
    runs-on: ubuntu-latest
    environment:
      Test
    steps:
    - run: echo "${{ vars.MIN_VARIABEL }}"
    - run: $MIN_VARIABEL
  print-my-other-variable:
    runs-on: ubuntu-latest
    environment:
      Production
    steps:
    - run: echo "${{ vars.MIN_VARIABEL }}"
    - run: $MIN_VARIABEL
